name: Free RDP (New Ngrok 3)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download New Ngrok v3
      run: |
        Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Connect Ngrok
      working-directory: ./ngrok
      run: |
        ./ngrok.exe config add-authtoken 2vO3AQdR1ETfyhAr3kW0OqM9Xx3_3T7RHt6oR2AHX7zqXimWa
        ./ngrok.exe tcp 3389

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
